### ISSUE TITLE
Where is the Sample code (* .php)? サンプルコード（*.php）は何処でしょうか？

### ISSUE THREAD

**Issue by sasakiss0922** [yamazakidaisuke/laravel_book#2]
[About]に、「Laravel本サンプルコードを公開」とありますが、
*.phpは、何処にありますでしょうか。
*.txt、*.zipしかないように見えます。

**Comment by yamazakidaisuke** [comment]
◇本書（Laravelフレームワーク）では章（Chapter）コマンドを使い、アプリケーションを構築していきます。
このリポジトリ内にある”.txt ”にコマンドの手順や、サンプルコード（ファイルを作成する手順）が順を追って記載されております。
※ステップバイステップで進める内容になっているため、このような構成になっています。

◇本書を始めやすくするための記事と動画も用意しました。
https://note.com/daisu_yamazaki/n/nd88acd31e322

ご回答になっておりますでしょうか？ 
また、ご参考になればと存じます。

**Comment by sasakiss0922** [comment]
ありがとうございます。
コマンドの手順や、ファイルを作成する手順が記載されていることが分かりました。

[About]に記載の、サンプルコードはどこにありますでしょうか？
回答いただけると、助かります。

**Comment by yamazakidaisuke** [comment]
>[About]に記載の、サンプルコードはどこにありますでしょうか？
>回答いただけると、助かります。
説明不足でした<m(__)m>

◇サンプル ダウンロード方法は、以下です。
１．この一つ上の階層「yamazakidaisuke/laravel_book」画面へ移動
２．「ＣＯＤＥ」という緑のボダンをクリック
３． Download.zip をクリック
でダウンロード可能です
※本書の全てのサンプルコード

◇このダウンロードしたファイル内の".txt"をChapter順にやっていきます。
１．コマンド（環境作る、必要なファイルを生成）
２．新規作成ファイル手順（PHPファイル）
３．新規作成したPHPファイルに内に".txt"で指示してる順番でコピー＆ペーストしていきます。
４．PHPコードとHTMLが載っているので、コード（部品）をコピーしてくみ上げていきます。
最終的に、Laravelフレームワークの作り方が身に付く流れになっております。

**Comment by sasakiss0922** [comment]
回答ありがとうございます。「CODE」からダウンロードでき、Auth.zipの内容を参照することができました。
（今までは、Auth.zipを右クリックメニューで名前を付けて保存していたため、解凍することができませんでした。）
これで、学習を継続していけます。
ありがとうございました。
